import { Factory, Seeder } from "typeorm-seeding";
import { Connection } from "typeorm";
import { User } from "../entity/User";
import { getRepository, Repository, DeleteResult } from "typeorm";

export default class CreateUsers implements Seeder {
  public async run(factory: Factory, connection: Connection): Promise<any> {
    await connection
      .createQueryBuilder()
      .insert()
      .into(User)
      .values([
        {
          first_name: "Penrod",
          last_name: "Saul",
          email: "psaul0@yandex.ru",
          gender: "Male",
          favoriteanimal: "Red-tailed phascogale",
          motto: "enable customized applications",
          networth: "$9.71B",
          carmake: "Honda",
          favmoviegenre: "Animation",
        },
        {
          first_name: "Cheslie",
          last_name: "Pesterfield",
          email: "cpesterfield1@plala.or.jp",
          gender: "Female",
          favoriteanimal: "Fox, grey",
          motto: "facilitate revolutionary metrics",
          networth: "$341.72M",
          carmake: "Land Rover",
          favmoviegenre: "Comedy|Documentary|Romance",
        },
        {
          first_name: "Francois",
          last_name: "Roberto",
          email: "froberto2@quantcast.com",
          gender: "Male",
          favoriteanimal: "White-bellied sea eagle",
          motto: "enhance strategic action-items",
          networth: "$61.01B",
          carmake: "Ford",
          favmoviegenre: "Action|Drama|War",
        },
        {
          first_name: "Beckie",
          last_name: "Ferryman",
          email: "bferryman3@e-recht24.de",
          gender: "Female",
          favoriteanimal: "Ringtail cat",
          motto: "exploit robust e-markets",
          networth: "$2.09B",
          carmake: "Volkswagen",
          favmoviegenre: "Documentary",
        },
        {
          first_name: "Eben",
          last_name: "Catonne",
          email: "ecatonne4@taobao.com",
          gender: "Male",
          favoriteanimal: "Red-knobbed coot",
          motto: "revolutionize vertical e-business",
          networth: "n/a",
          carmake: "Maserati",
          favmoviegenre: "Action|Crime|Thriller",
        },
        {
          first_name: "Jackie",
          last_name: "Cockerell",
          email: "jcockerell5@cam.ac.uk",
          gender: "Female",
          favoriteanimal: "Blacksmith plover",
          motto: "repurpose customized networks",
          networth: "$16.13M",
          carmake: "Subaru",
          favmoviegenre: "Comedy",
        },
        {
          first_name: "Locke",
          last_name: "Cino",
          email: "lcino6@godaddy.com",
          gender: "Male",
          favoriteanimal: "Klipspringer",
          motto: "facilitate integrated schemas",
          networth: "$858.82M",
          carmake: "Chevrolet",
          favmoviegenre: "Drama",
        },
        {
          first_name: "Saxon",
          last_name: "Hryncewicz",
          email: "shryncewicz7@mail.ru",
          gender: "Male",
          favoriteanimal: "South American sea lion",
          motto: "whiteboard clicks-and-mortar systems",
          networth: "$1.59B",
          carmake: "Chevrolet",
          favmoviegenre: "Children|Comedy",
        },
        {
          first_name: "Killy",
          last_name: "Brane",
          email: "kbrane8@time.com",
          gender: "Male",
          favoriteanimal: "Elephant, asian",
          motto: "morph interactive convergence",
          networth: "$6.6B",
          carmake: "Mercedes-Benz",
          favmoviegenre: "Crime|Drama|Mystery|Thriller",
        },
        {
          first_name: "Ermentrude",
          last_name: "Futter",
          email: "efutter9@amazonaws.com",
          gender: "Female",
          favoriteanimal: "Lion, galapagos sea",
          motto: "leverage sticky models",
          networth: "$43.1B",
          carmake: "GMC",
          favmoviegenre: "Documentary",
        },
        {
          first_name: "Tomasine",
          last_name: "Mainston",
          email: "tmainstona@mit.edu",
          gender: "Female",
          favoriteanimal: "Bobcat",
          motto: "mesh seamless platforms",
          networth: "$7.19B",
          carmake: "Ford",
          favmoviegenre: "Drama|Thriller",
        },
        {
          first_name: "Brinna",
          last_name: "Tibbles",
          email: "btibblesb@time.com",
          gender: "Female",
          favoriteanimal: "Yellow-headed caracara",
          motto: "grow leading-edge partnerships",
          networth: "$131.24M",
          carmake: "Toyota",
          favmoviegenre: "Drama|Romance",
        },
        {
          first_name: "Marketa",
          last_name: "Denver",
          email: "mdenverc@godaddy.com",
          gender: "Female",
          favoriteanimal: "Small-spotted genet",
          motto: "scale extensible e-commerce",
          networth: "$121.52M",
          carmake: "Ford",
          favmoviegenre: "Comedy|Documentary|Drama",
        },
        {
          first_name: "Sheryl",
          last_name: "Odhams",
          email: "sodhamsd@rediff.com",
          gender: "Female",
          favoriteanimal: "Eland, common",
          motto: "envisioneer open-source channels",
          networth: "$1.28B",
          carmake: "Dodge",
          favmoviegenre: "Drama|Romance",
        },
        {
          first_name: "Ebeneser",
          last_name: "Jeger",
          email: "ejegere@guardian.co.uk",
          gender: "Male",
          favoriteanimal: "Stork, marabou",
          motto: "target bricks-and-clicks users",
          networth: "n/a",
          carmake: "Ford",
          favmoviegenre: "Drama",
        },
        {
          first_name: "Hildegarde",
          last_name: "Aartsen",
          email: "haartsenf@seattletimes.com",
          gender: "Female",
          favoriteanimal: "Painted stork",
          motto: "morph collaborative niches",
          networth: "$50.2B",
          carmake: "Infiniti",
          favmoviegenre: "Comedy",
        },
        {
          first_name: "Clerissa",
          last_name: "Van Giffen",
          email: "cvangiffeng@angelfire.com",
          gender: "Female",
          favoriteanimal: "Plover, blacksmith",
          motto: "disintermediate front-end portals",
          networth: "$100.76M",
          carmake: "BMW",
          favmoviegenre: "Documentary",
        },
        {
          first_name: "Naoma",
          last_name: "Easun",
          email: "neasunh@symantec.com",
          gender: "Female",
          favoriteanimal: "Skua, great",
          motto: "synthesize user-centric content",
          networth: "$1.32B",
          carmake: "Toyota",
          favmoviegenre: "Animation",
        },
        {
          first_name: "Renata",
          last_name: "Cale",
          email: "rcalei@hud.gov",
          gender: "Female",
          favoriteanimal: "Sunbird, lesser double-collared",
          motto: "revolutionize enterprise ROI",
          networth: "$133.85M",
          carmake: "Mercedes-Benz",
          favmoviegenre: "Comedy",
        },
        {
          first_name: "Mitchell",
          last_name: "Whalebelly",
          email: "mwhalebellyj@mediafire.com",
          gender: "Male",
          favoriteanimal: "Eagle, long-crested hawk",
          motto: "recontextualize web-enabled solutions",
          networth: "$51.65M",
          carmake: "GMC",
          favmoviegenre: "Drama|War",
        },
        {
          first_name: "Wynny",
          last_name: "Gallaway",
          email: "wgallawayk@cafepress.com",
          gender: "Female",
          favoriteanimal: "Phalarope, northern",
          motto: "matrix cutting-edge applications",
          networth: "n/a",
          carmake: "Mercury",
          favmoviegenre: "Comedy|Drama",
        },
        {
          first_name: "Sheilakathryn",
          last_name: "McElree",
          email: "smcelreel@economist.com",
          gender: "Female",
          favoriteanimal: "Western pygmy possum",
          motto: "cultivate virtual interfaces",
          networth: "$1.19B",
          carmake: "Mercury",
          favmoviegenre: "Action|Crime|Thriller",
        },
        {
          first_name: "Elysha",
          last_name: "Wellwood",
          email: "ewellwoodm@chronoengine.com",
          gender: "Female",
          favoriteanimal: "Tinamou, elegant crested",
          motto: "maximize virtual applications",
          networth: "$184.63M",
          carmake: "GMC",
          favmoviegenre: "Drama|Romance|War",
        },
        {
          first_name: "Minna",
          last_name: "Clues",
          email: "mcluesn@yelp.com",
          gender: "Female",
          favoriteanimal: "Deer, spotted",
          motto: "evolve sticky partnerships",
          networth: "$34.78M",
          carmake: "Dodge",
          favmoviegenre: "Comedy|Romance",
        },
        {
          first_name: "Freeland",
          last_name: "Pinnegar",
          email: "fpinnegaro@usatoday.com",
          gender: "Male",
          favoriteanimal: "Squirrel, pine",
          motto: "strategize integrated applications",
          networth: "$113.08B",
          carmake: "Lexus",
          favmoviegenre: "Drama|Sci-Fi",
        },
        {
          first_name: "Kariotta",
          last_name: "Spensly",
          email: "kspenslyp@networksolutions.com",
          gender: "Female",
          favoriteanimal: "Monitor, water",
          motto: "transition web-enabled web services",
          networth: "n/a",
          carmake: "Saab",
          favmoviegenre: "Action|Adventure|Children|Fantasy",
        },
        {
          first_name: "Lockwood",
          last_name: "Grain",
          email: "lgrainq@themeforest.net",
          gender: "Male",
          favoriteanimal: "Bushbaby, large-eared",
          motto: "facilitate holistic mindshare",
          networth: "$1.19B",
          carmake: "Hyundai",
          favmoviegenre: "Action|Comedy|Crime|Mystery",
        },
        {
          first_name: "Blaire",
          last_name: "Bowlesworth",
          email: "bbowlesworthr@example.com",
          gender: "Female",
          favoriteanimal: "Pintail, bahama",
          motto: "grow 24/365 web-readiness",
          networth: "$1.72B",
          carmake: "Kia",
          favmoviegenre: "Comedy|Western",
        },
        {
          first_name: "Dennison",
          last_name: "Frascone",
          email: "dfrascones@sphinn.com",
          gender: "Male",
          favoriteanimal: "Magpie, australian",
          motto: "reinvent impactful vortals",
          networth: "$261.63M",
          carmake: "Honda",
          favmoviegenre: "Crime|Horror|Thriller",
        },
        {
          first_name: "Evangelin",
          last_name: "Ardern",
          email: "eardernt@gravatar.com",
          gender: "Female",
          favoriteanimal: "Snake, green vine",
          motto: "engage viral applications",
          networth: "$52.6M",
          carmake: "Infiniti",
          favmoviegenre: "Action|Crime|Drama",
        },
      ])
      .execute();
  }
}
